include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_print: false
    require_trailing_commas: false
    cancel_subscriptions: false
    avoid_positional_boolean_parameters: false
