name: icebr8k
description: Icebr8k app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.14.0-2.0.dev <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  firebase_storage: ^10.0.3
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_linkify: ^5.0.2
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_zoom_drawer: ^2.1.1
  geoflutterfire: ^3.0.1
  get: ^4.3.8
  get_storage: ^2.0.3
  google_sign_in: ^5.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  intl: ^0.17.0
  json_annotation: ^4.1.0
  liquid_swipe: ^2.1.0
  location: ^4.3.0
  lottie: ^1.1.0
  move_to_background: ^1.0.2
  page_flip_builder: ^0.1.3
  pull_to_refresh: ^2.0.0
  sign_in_with_apple: ^3.0.0
  syncfusion_flutter_datepicker: ^19.2.62
  uuid: ^3.0.4




dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^5.0.1

  lint: ^1.7.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_android.png"
  image_path_ios: "assets/icons/logo_ios.png"


