// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfthU0Ttphr4FR9yCtIM9Y1WrHnW3qdo',
    appId: '1:768747685028:android:5a62261de5514c86891231',
    messagingSenderId: '768747685028',
    projectId: 'icebr8k-flutter',
    databaseURL: 'https://icebr8k-flutter.firebaseio.com',
    storageBucket: 'icebr8k-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJQvz1y5PgoxcEm21EvArc-mj5gnwuH8',
    appId: '1:768747685028:ios:13fa52e1a53676b5891231',
    messagingSenderId: '768747685028',
    projectId: 'icebr8k-flutter',
    databaseURL: 'https://icebr8k-flutter.firebaseio.com',
    storageBucket: 'icebr8k-flutter.appspot.com',
    androidClientId: '768747685028-678o14pg45csliljg9tavp1c9on1gnl3.apps.googleusercontent.com',
    iosClientId: '768747685028-rmga7acnpvd762cj9kmeo5d4vtrnnv2d.apps.googleusercontent.com',
    iosBundleId: 'com.icebr8k.ios',
  );
}
